version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    container_name: my-jenkins
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: